myscrumy/django-moshoodscrumy/moshoodscrumy/urls.py
from django.urls import path, include
from moshoodscrumy import views

urlpatterns = [
    path('', views.index),
    
]

myscrumy/moshoodscrumy/urls.py
from django.urls import path, include
from moshoodscrumy import views

app_name = 'moshoodscrumy'
urlpatterns = [
    path('movegoal/<int:goal_id>', views.move_goal, name='movegoal'),
    path('', views.index),
    path('addgoal/', views.add_goal, name='addgoal'),
    path('home/', views.home, name='about'),
    path('accounts/', include('django.contrib.auth.urls')), # Lab16 Task One
]

myscrumy/myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('moshoodscrumy/', include('moshoodscrumy.urls'), name='moshoodscrumy')
    path('moshoodscrumy/', include('moshoodscrumy.urls', namespace='moshoodscrumy')),
    path('websocket/', include('websocket.urls')),
]

myscrumy/django-moshoodscrumy/moshoodscrumy/models.py
from django.db import models

# Create your models here.

myscrumy/moshoodscrumy/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class GoalStatus(models.Model):
	status_name = models.CharField(max_length=300)
	def __str__(self):
		return self.status_name

class ScrumyGoals(models.Model):
	goal_name = models.CharField(max_length=300)
	goal_id = models.IntegerField()
	created_by = models.CharField(max_length=300)
	moved_by = models.CharField(max_length=300)
	owner = models.CharField(max_length=300)
	goal_status = models.ForeignKey(GoalStatus, on_delete=models.PROTECT)
	user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user_to_scrumy')
	def __str__(self):
		return self.goal_name

class ScrumyHistory(models.Model):
	moved_by = models.CharField(max_length=300)
	created_by = models.CharField(max_length=300)
	moved_from = models.CharField(max_length=300)
	moved_to = models.CharField(max_length=300)
	time_of_action = models.DateTimeField(auto_now_add=True,null=True)
	goal = models.ForeignKey(ScrumyGoals, on_delete=models.PROTECT)
	def __str__(self):
		return self.created_by

myscrumy/moshoodscrumy/forms.py
from django.forms import ModelForm, TextInput
from .models import ScrumyGoals
from django.contrib.auth.models import User

class SignupForm(ModelForm):
    class Meta:
        model = User
        fields = [ 'first_name','last_name','email','username','password']

class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'user']

myscrumy/django-moshoodscrumy/moshoodscrumy/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse


def index(request):
	return HttpResponse("Welcome to Django") 

myscrumy/moshoodscrumy/views.py
from django.shortcuts import render

# Create your views here.
import random

from django.http import HttpResponse
from .models import ScrumyGoals, GoalStatus
from django.contrib.auth.models import User
from django.contrib.auth.models import Group 
from .forms import SignupForm, CreateGoalForm

def index(request):
	form = SignupForm() 
	if request.method == 'POST': 
		form = SignupForm(request.POST)
		form.save()
		user = User.objects.get(username=request.POST['username'])
		my_group = Group.objects.get(name = 'Developer') 
		my_group.user_set.add(user)
		if user.groups.filter(name='Developer').exists() :
			return render(request, 'moshoodscrumy/success.html') 
	else: 
		form = SignupForm()
	return render(request, 'moshoodscrumy/index.html', {'form':form}) 

def move_goal(request, **kwargs):
	# output = ScrumyGoals.objects.get(goal_id=kwargs['goal_id'])
	# return HttpResponse(output)
	
	## LAB 14
	# dictionary = {'error': 'A record with that goal id does not exist'}
	# try: 
	# 	obj = ScrumyGoals.objects.get(goal_id=kwargs['goal_id'])
	# except Exception as e: 
	# 	return render(request, 'moshoodscrumy/exception.html', dictionary) 
	# else: 
	# 	return HttpResponse(obj.goal_name)

	## LAB 21
	dictionary = {'pass': 'Successfully'}
	if request.method == 'POST':
		if request.user.groups.filter(name='Developer').exists():
			obj = ScrumyGoals.objects.get(goal_id=kwargs['goal_id'])
			if request.user == obj.user :
				if request.POST['goal_status'] == 'Done Goal':
					return HttpResponse('You are a developer')
				else:
					obj.goal_status = GoalStatus(status_name=request.POST['goal_status'])
					obj.goal_status.save()
					obj.save()
					return render(request, 'moshoodscrumy/exception.html', dictionary)
			else:
				return HttpResponse('Not the owner')
		elif request.user.groups.filter(name='Quality Assurance').exists():
			obj = ScrumyGoals.objects.get(goal_id=kwargs['goal_id'])
			if request.user == obj.user :
					obj.goal_status = GoalStatus(status_name=request.POST['goal_status'])
					obj.goal_status.save()
					obj.save()
					return render(request, 'moshoodscrumy/exception.html', dictionary)
			else:
				if request.POST['goal_status'] == 'Done Goal':
					obj.goal_status = GoalStatus(status_name=request.POST['goal_status'])
					obj.goal_status.save()
					obj.save()
					return render(request, 'moshoodscrumy/exception.html', dictionary)
				else:
					return HttpResponse('Not the owner')
		elif request.user.groups.filter(name='Owner').exists():
			obj = ScrumyGoals.objects.get(goal_id=kwargs['goal_id'])
			if request.user == obj.user :
					obj.goal_status = GoalStatus(status_name=request.POST['goal_status'])
					obj.goal_status.save()
					obj.save()
					return render(request, 'moshoodscrumy/exception.html', dictionary)
			else:
				return HttpResponse('Not the owner')
		elif request.user.groups.filter(name='Admin').exists():
			obj = ScrumyGoals.objects.get(goal_id=kwargs['goal_id'])
			obj.goal_status = GoalStatus(status_name=request.POST['goal_status'])
			obj.goal_status.save()
			obj.save()
			return render(request, 'moshoodscrumy/exception.html', dictionary)
		else:
			return render(request, 'moshoodscrumy/exception.html')
	else:
		return render(request, 'moshoodscrumy/exception.html')
		

def add_goal(request):
	# add_goal = ScrumyGoals.objects.create(goal_name = 'Keep Learning Django', goal_id = random.randrange(1000, 9999, 2), created_by = 'Louis', moved_by = 'Louis', owner = 'Louis', goal_status = GoalStatus.objects.get(status_name='Weekly Goal'), user = User.objects.get(username='louis'))
	# add_goal.save()
	# return HttpResponse('Saved Successfully')
	form = CreateGoalForm() 
	if request.method == 'POST': 
		form = CreateGoalForm(request.POST)
		good_to_go = form.save(commit=False) 
		good_to_go.goal_id = random.randrange(1000, 9999, 2)
		good_to_go.created_by = 'Louis'
		good_to_go.moved_by = 'Louis'
		good_to_go.owner = 'Louis' 
		good_to_go.goal_status = GoalStatus(status_name='Weekly Goal')
		good_to_go.goal_status.save()
		good_to_go.save()
		# user = User.objects.get(username=request.user)
		# my_group = Group.objects.get(name = 'Developer') 
		# my_group.user_set.add(user)
		# if user.groups.filter(name='Developer').exists() :
		# 	return render(request, 'moshoodscrumy/success.html') 
	else: 
		form = CreateGoalForm()

	return render(request, 'moshoodscrumy/goal.html', {'form':form}) 

def home(request):
	# ## LAB 12
	# # goal = ScrumyGoals.objects.all()
	# goal = ScrumyGoals.objects.get(goal_name='Keep Learning Django')
	# # output = ', '.join([eachgoal.goal_name for eachgoal in goal])
	# # return HttpResponse(output)
	# return HttpResponse(goal)

	## LAB 13
	# dictionary = {}
	# goal = ScrumyGoals.objects.get(goal_name='Learn Django')
	# dictionary['goal_name'] = goal.goal_name
	# dictionary['goal_id'] = goal.goal_id
	# dictionary['user'] = goal.user 
	# return render(request, 'moshoodscrumy/home.html', dictionary)

	## LAB 15
	dictionary = {}
	users = User.objects.all()
	# weekly_goals = ScrumyGoals.objects.filter(goal_status=GoalStatus.objects.get(status_name='Weekly Goal'))
	# daily_goals = ScrumyGoals.objects.filter(goal_status=GoalStatus.objects.get(status_name='Daily Goal'))
	# verify_goals = ScrumyGoals.objects.filter(goal_status=GoalStatus.objects.get(status_name='Verify Goal'))
	# done_goals = ScrumyGoals.objects.filter(goal_status=GoalStatus.objects.get(status_name='Done Goal'))
	# dictionary['weekly_goals'] = '  '.join([eachgoal_1.goal_name for eachgoal_1 in weekly_goals])
	# dictionary['daily_goals'] = '  '.join([eachgoal_1.goal_name for eachgoal_1 in daily_goals])
	# dictionary['verify_goals'] = '  '.join([eachgoal_1.goal_name for eachgoal_1 in verify_goals])
	# dictionary['done_goals'] = '  '.join([eachgoal_1.goal_name for eachgoal_1 in done_goals])
	dictionary['users'] = users 
	# dictionary['user_real'] = '  '.join([eachgoal_1.username for eachgoal_1 in users])
	return render(request, 'moshoodscrumy/home.html', dictionary)

	##Lab18
	# return render(request, 'moshoodscrumy/home.html')	

myscrumy/moshoodscrumy/templates/moshoodscrumy/e.html
<!DOCTYPE html>
<html>
<head>
	<title>Moshood Scrumy</title>
	<style>
		table, th, td {
		  border: 1px solid black;
		  border-collapse: collapse;
		}
		th, td {
		  padding: 5px;
		  text-align: left;    
		}
	</style>
</head>
<body>
	<table style="width:100%">
		<tr>
			<th>User</th>
			<th>Weekly Goals</th>
			<th>Daily Goals</th>
			<th>Verify Goals</th>
			<th>Done Goals</th> 
		</tr>
		<tr>
			<th>{{user_real}}</th> 
			<th>{{weekly_goals}}</th> 
			<th>{{daily_goals}}</th> 
			<th>{{verify_goals}}</th> 
			<th>{{done_goals}}</th> 
		</tr>
	</table>
	
</body>
</html>


<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
</head>
<body>
	<a href="{% url 'about' %}"> About us </a>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
	<title>home</title>
</head>
<body>
	<a href="{% url 'moshoodscrumy:addgoal' %}">Home</a>
</body>
</html>

myscrumy/moshoodscrumy/templates/moshoodscrumy/exception.html
<!DOCTYPE html>
<html>
<head>
	<title>Goal</title>
</head>
<body>
	<h1>{{pass}}</h1>
	<form method="post">
		{% csrf_token %} 
		 
		 	<select name="goal_status">
		 		<option value="Weekly Goal">Weekly Goal</option>
		 		<option value="Daily Goal">Daily Goal</option>
		 		<option value="Verify Goal">Verify Goal</option>
		 		<option value="Done Goal">Done Goal</option>
		 	</select>
		 
		 <input type="submit"></input>
	</form>
</body>

myscrumy/moshoodscrumy/templates/moshoodscrumy/goal.html
<!DOCTYPE html>
<html>
<head>
	<title>Goal</title>
</head>
<body>
	<a href="{% url 'moshoodscrumy:about' %}">About us</a>
	<form method="post">
		{% csrf_token %} 
		 {{form}}
		 <input type="submit">Goal</input>
	</form>
</body>

myscrumy/moshoodscrumy/templates/moshoodscrumy/home.html
<!DOCTYPE html>
<html>
<head>
	<title>Moshood Scrumy</title>
	<style>
		table, th, td {
		  border: 1px solid black;
		  border-collapse: collapse;
		}
		th, td {
		  padding: 5px;
		  text-align: left;    
		}
	</style>
</head>
<body>
	<table style="width:100%">
		<tr>
			<th>Users</th>
			<th>Weekly Goals</th>
			<th>Daily Goals</th>
			<th>Verify Goals</th>
			<th>Done Goals</th> 
		</tr>
		{% for user in users %}
		<tr>
			<td class="user" rowspan="{{user.user_to_scrumy.count}}">{{ user }}</td>
			{% for goal in user.user_to_scrumy.all %}
			<tr>
			{% if goal.goal_status.status_name == 'Weekly Goal' %}
				<td> <a href="{% url 'moshoodscrumy:movegoal' goal.goal_id %}">Link</a> {{goal.goal_id}}  {{ goal.goal_name }}</td>
				<td></td>
				<td></td>
				<td></td>
			{% elif goal.goal_status.status_name == 'Daily Goal'%}
				<td></td>
				<td> <a href="{% url 'moshoodscrumy:movegoal' goal.goal_id %}">Link</a> {{goal.goal_id}}  {{ goal.goal_name }}</td>
				<td></td>
				<td></td>
			{% elif goal.goal_status.status_name == 'Verify Goal'%}
				<td></td>
				<td></td>
				<td> <a href="{% url 'moshoodscrumy:movegoal' goal.goal_id %}">Link</a> {{goal.goal_id}}  {{ goal.goal_name }}</td>
				<td></td>
			{% else %}
				<td></td>
				<td></td>
				<td></td>
				<td> <a href="{% url 'moshoodscrumy:movegoal' goal.goal_id %}">Link</a> {{goal.goal_id}}  {{ goal.goal_name }}</td>
			{% endif %}
			</tr>
			{% endfor %}
		</tr>
		{% endfor %}
	</table>
	<script>
		let userRow = document.getElementsByClassName('user');
		for (var i = 0; i < userRow.length; i++) {
			userRow[i].rowSpan += 1
		}
	</script>
</body>
</html>

myscrumy/moshoodscrumy/templates/moshoodscrumy/index.html
<!DOCTYPE html>
<html>
<head>
	<title>SignUp</title>
</head>
<body>
	<a href="{% url 'moshoodscrumy:about' %}">About us</a>
	<form method="post">
		{% csrf_token %} 
		 {{form}}
	</form>
</body>

myscrumy/moshoodscrumy/templates/moshoodscrumy/success.html
<!DOCTYPE html>
<html>
<head>
	<title>Success</title>
</head>
<body>
	<p>Your account has been created successfully</p>
</body>
</html>